_BASE_: [
  '../datasets/invs.yml',
  '../runtime.yml',
  '_base_/optimizer_1700e.yml',
  '_base_/ssdlite_mobilenet_v3_large_320.yml',
  '_base_/ssdlite320_reader.yml',
]
weights: output/ssdlite_mobilenet_v3_large_320_invs/model_final
